export type PlayerRole = 'WK' | 'BAT' | 'AR' | 'BOWL';

export interface Player {
  id: string;
  name: string;
  team: string;
  role: PlayerRole;
  credits: number;
}

function p(team: string, idx: number, name: string, role: PlayerRole, credits: number = 7.0): Player {
  return { id: `${team.toLowerCase()}-${idx}`, name, team, role, credits };
}

export const IPL_PLAYERS: Player[] = [
  // ── CSK ──
  p('CSK', 1, 'MS Dhoni', 'WK', 7.5),
  p('CSK', 2, 'Sanju Samson', 'WK', 9.0),
  p('CSK', 3, 'Kuldeep Sharma', 'WK', 6.5),
  p('CSK', 4, 'Urvil Patel', 'WK', 7.0),
  p('CSK', 5, 'Ruturaj Gaikwad', 'BAT', 9.0),
  p('CSK', 6, 'Dewald Brevis', 'BAT', 8.5),
  p('CSK', 7, 'Ayush Mhatre', 'BAT', 7.5),
  p('CSK', 8, 'Shahrukh Khan', 'BAT', 7.0),
  p('CSK', 9, 'Jamie Overton', 'AR', 7.5),
  p('CSK', 10, 'Ramakrishna Ghosh', 'AR', 6.0),
  p('CSK', 11, 'Prashant Veer', 'AR', 6.5),
  p('CSK', 12, 'Matthew Short', 'AR', 7.0),
  p('CSK', 13, 'Aman Khan', 'AR', 6.0),
  p('CSK', 14, 'Zak Foulkes', 'AR', 6.5),
  p('CSK', 15, 'Shivam Dube', 'AR', 8.5),
  p('CSK', 16, 'Khaleel Ahmed', 'BOWL', 8.0),
  p('CSK', 17, 'Noor Ahmad', 'BOWL', 8.5),
  p('CSK', 18, 'Anshul Kamboj', 'BOWL', 6.5),
  p('CSK', 19, 'Mukesh Choudhary', 'BOWL', 7.0),
  p('CSK', 20, 'Shreyas Gopal', 'BOWL', 7.0),
  p('CSK', 21, 'Gurjapneet Singh', 'BOWL', 6.0),
  p('CSK', 22, 'Akeal Hosein', 'BOWL', 7.5),
  p('CSK', 23, 'Matt Henry', 'BOWL', 8.0),
  p('CSK', 24, 'Rahul Chahar', 'BOWL', 7.0),
  p('CSK', 25, 'Spencer Johnson', 'BOWL', 8.0),

  // ── MI ──
  p('MI', 1, 'Rohit Sharma', 'BAT', 9.0),
  p('MI', 2, 'Suryakumar Yadav', 'BAT', 9.0),
  p('MI', 3, 'Danish Malewar', 'BAT', 6.0),
  p('MI', 4, 'Tilak Varma', 'BAT', 8.5),
  p('MI', 5, 'Robin Minz', 'WK', 6.5),
  p('MI', 6, 'Sherfane Rutherford', 'BAT', 8.0),
  p('MI', 7, 'Ryan Rickelton', 'WK', 8.0),
  p('MI', 8, 'Quinton de Kock', 'WK', 8.5),
  p('MI', 9, 'Hardik Pandya', 'AR', 9.0),
  p('MI', 10, 'Naman Dhir', 'BAT', 7.5),
  p('MI', 11, 'Mitchell Santner', 'AR', 8.0),
  p('MI', 12, 'Raj Angad Bawa', 'AR', 6.0),
  p('MI', 13, 'Atharva Ankolekar', 'AR', 6.5),
  p('MI', 14, 'Mayank Rawat', 'AR', 6.0),
  p('MI', 15, 'Corbin Bosch', 'AR', 7.5),
  p('MI', 16, 'Will Jacks', 'AR', 8.0),
  p('MI', 17, 'Shardul Thakur', 'BOWL', 7.5),
  p('MI', 18, 'Trent Boult', 'BOWL', 8.5),
  p('MI', 19, 'Mayank Markande', 'BOWL', 7.0),
  p('MI', 20, 'Deepak Chahar', 'BOWL', 8.0),
  p('MI', 21, 'Ashwani Kumar', 'BOWL', 7.0),
  p('MI', 22, 'Raghu Sharma', 'BOWL', 6.5),
  p('MI', 23, 'Mohammad Izhar', 'BOWL', 6.5),
  p('MI', 24, 'Allah Ghazanfar', 'BOWL', 7.5),
  p('MI', 25, 'Jasprit Bumrah', 'BOWL', 9.0),

  // ── RCB ──
  // WK
  p('RCB', 1, 'Phil Salt', 'WK', 9.0),
  p('RCB', 2, 'Jitesh Sharma', 'WK', 8.0),
  p('RCB', 3, 'Jordan Cox', 'WK', 6.5),
  // BAT
  p('RCB', 4, 'Virat Kohli', 'BAT', 9.0),
  p('RCB', 5, 'Rajat Patidar', 'BAT', 8.5),
  p('RCB', 6, 'Tim David', 'BAT', 8.0),
  p('RCB', 7, 'Jacob Bethell', 'BAT', 8.0),
  p('RCB', 8, 'Devdutt Padikkal', 'BAT', 7.5),
  p('RCB', 9, 'Venkatesh Iyer', 'BAT', 7.5),
  // AR
  p('RCB', 10, 'Krunal Pandya', 'AR', 8.5),
  p('RCB', 11, 'Romario Shepherd', 'AR', 8.0),
  p('RCB', 12, 'Swapnil Singh', 'AR', 6.5),
  p('RCB', 13, 'Vihaan Malhotra', 'AR', 6.5),
  p('RCB', 14, 'Kanishk Chouhan', 'AR', 6.0),
  // BOWL
  p('RCB', 15, 'Josh Hazlewood', 'BOWL', 9.0),
  p('RCB', 16, 'Bhuvneshwar Kumar', 'BOWL', 8.5),
  p('RCB', 17, 'Nuwan Thushara', 'BOWL', 8.0),
  p('RCB', 18, 'Jacob Duffy', 'BOWL', 8.0),
  p('RCB', 19, 'Suyash Sharma', 'BOWL', 7.5),
  p('RCB', 20, 'Yash Dayal', 'BOWL', 7.5),
  p('RCB', 21, 'Rasikh Salam', 'BOWL', 6.5),
  p('RCB', 22, 'Abhinandan Singh', 'BOWL', 6.0),
  p('RCB', 23, 'Satvik Deswal', 'BOWL', 6.0),
  p('RCB', 24, 'Mangesh Yadav', 'BOWL', 6.5),
  p('RCB', 25, 'Vicky Ostwal', 'BOWL', 6.5),

  // ── KKR ──
  p('KKR', 1, 'Ajinkya Rahane', 'BAT', 8.0),
  p('KKR', 2, 'Rinku Singh', 'BAT', 8.0),
  p('KKR', 3, 'Angkrish Raghuvanshi', 'BAT', 7.5),
  p('KKR', 4, 'Manish Pandey', 'BAT', 6.5),
  p('KKR', 5, 'Rahul Tripathi', 'BAT', 7.0),
  p('KKR', 6, 'Finn Allen', 'WK', 8.5),
  p('KKR', 7, 'Tanu Dahiya Singh', 'WK', 6.0),
  p('KKR', 8, 'Tim Seifert', 'WK', 8.0),
  p('KKR', 9, 'Rovman Powell', 'BAT', 7.5),
  p('KKR', 10, 'Anukul Sudhakar Roy', 'AR', 7.0),
  p('KKR', 11, 'Cameron Green', 'AR', 8.5),
  p('KKR', 12, 'Sarthak Ranjan', 'BAT', 6.0),
  p('KKR', 13, 'Daksh Kamra', 'AR', 6.5),
  p('KKR', 14, 'Rachin Ravindra', 'AR', 7.5),
  p('KKR', 15, 'Ramandeep Singh', 'AR', 7.0),
  p('KKR', 16, 'Sunil Narine', 'AR', 8.5),
  p('KKR', 17, 'Blessing Muzarabani', 'BOWL', 7.0),
  p('KKR', 18, 'Vaibhav Arora', 'BOWL', 8.0),
  p('KKR', 19, 'Matheesha Pathirana', 'BOWL', 8.0),
  p('KKR', 20, 'Kartik Tyagi', 'BOWL', 7.0),
  p('KKR', 21, 'Prashant Solanki', 'BOWL', 6.5),
  p('KKR', 22, 'Saurabh Dubey', 'BOWL', 6.0),
  p('KKR', 23, 'Navdeep Saini', 'BOWL', 7.5),
  p('KKR', 24, 'Umran Malik', 'BOWL', 6.5),
  p('KKR', 25, 'Varun Chakaravarthy', 'BOWL', 9.0),

  // ── SRH ──
  // WK
  p('SRH', 1, 'Ishan Kishan', 'WK', 9.0),
  p('SRH', 2, 'Heinrich Klaasen', 'WK', 8.5),
  p('SRH', 3, 'Salil Arora', 'WK', 6.0),
  // BAT
  p('SRH', 4, 'Abhishek Sharma', 'BAT', 9.0),
  p('SRH', 5, 'Travis Head', 'BAT', 9.0),
  p('SRH', 6, 'Aniket Verma', 'BAT', 7.0),
  p('SRH', 7, 'Smaran Ravichandran', 'BAT', 6.5),
  p('SRH', 8, 'Shivang Kumar', 'BAT', 6.0),
  // AR
  p('SRH', 9, 'Nitish Kumar Reddy', 'AR', 8.0),
  p('SRH', 10, 'Liam Livingstone', 'AR', 8.0),
  p('SRH', 11, 'Kamindu Mendis', 'AR', 7.5),
  p('SRH', 12, 'Harsh Dubey', 'AR', 7.0),
  // BOWL
  p('SRH', 13, 'Pat Cummins', 'BOWL', 8.5),
  p('SRH', 14, 'Harshal Patel', 'BOWL', 8.0),
  p('SRH', 15, 'Brydon Carse', 'BOWL', 7.5),
  p('SRH', 16, 'Zeeshan Ansari', 'BOWL', 7.5),
  p('SRH', 17, 'Jaydev Unadkat', 'BOWL', 7.0),
  p('SRH', 18, 'Eshan Malinga', 'BOWL', 7.0),
  p('SRH', 19, 'David Payne', 'BOWL', 7.0),
  p('SRH', 20, 'Shivam Mavi', 'BOWL', 7.0),
  p('SRH', 21, 'Sakib Hussain', 'BOWL', 6.0),
  p('SRH', 22, 'Onkar Tarmale', 'BOWL', 5.5),
  p('SRH', 23, 'Amit Kumar', 'BOWL', 6.0),
  p('SRH', 24, 'Praful Hinge', 'BOWL', 6.5),
  p('SRH', 25, 'Krains Fuletra', 'BOWL', 5.5),

  // ── DC ──
  p('DC', 1, 'Karun Nair', 'BAT', 8.0),
  p('DC', 2, 'David Miller', 'BAT', 8.0),
  p('DC', 3, 'Pathum Nissanka', 'BAT', 6.0),
  p('DC', 4, 'Sahil Parakh', 'BAT', 6.0),
  p('DC', 5, 'Prithvi Shaw', 'BAT', 8.0),
  p('DC', 6, 'KL Rahul', 'WK', 9.5),
  p('DC', 7, 'Ben Duckett', 'WK', 7.5),
  p('DC', 8, 'Abishek Porel', 'WK', 6.5),
  p('DC', 9, 'Tristan Stubbs', 'WK', 7.5),
  p('DC', 10, 'Axar Patel', 'AR', 8.5),
  p('DC', 11, 'Sameer Rizvi', 'AR', 6.5),
  p('DC', 12, 'Ashutosh Sharma', 'AR', 6.5),
  p('DC', 13, 'Vipraj Nigam', 'AR', 6.0),
  p('DC', 14, 'Ajay Mandal', 'AR', 6.0),
  p('DC', 15, 'Tripurana Vijay', 'AR', 6.0),
  p('DC', 16, 'Madhav Tiwari', 'AR', 6.0),
  p('DC', 17, 'Nitish Rana', 'AR', 7.5),
  p('DC', 18, 'Mitchell Starc', 'BOWL', 9.5),
  p('DC', 19, 'T Natarajan', 'BOWL', 7.0),
  p('DC', 20, 'Mukesh Kumar', 'BOWL', 7.0),
  p('DC', 21, 'Dushmantha Chameera', 'BOWL', 6.0),
  p('DC', 22, 'Auqib Nabi', 'BOWL', 6.0),
  p('DC', 23, 'Lungisani Ngidi', 'BOWL', 6.0),
  p('DC', 24, 'Kyle Jamieson', 'BOWL', 7.0),
  p('DC', 25, 'Kuldeep Yadav', 'BOWL', 8.5),

  // ── PBKS ──
  p('PBKS', 1, 'Shreyas Iyer', 'BAT', 9.0),
  p('PBKS', 2, 'Nehal Wadhera', 'BAT', 7.5),
  p('PBKS', 3, 'Harnoor Pannu', 'BAT', 6.0),
  p('PBKS', 4, 'Pyla Avinash', 'BAT', 6.5),
  p('PBKS', 5, 'Shashank Singh', 'BAT', 8.0),
  p('PBKS', 6, 'Vishnu Vinod', 'WK', 7.0),
  p('PBKS', 7, 'Prabhsimran Singh', 'WK', 8.0),
  p('PBKS', 8, 'Marcus Stoinis', 'AR', 8.0),
  p('PBKS', 9, 'Harpreet Brar', 'BOWL', 7.5),
  p('PBKS', 10, 'Marco Jansen', 'AR', 8.5),
  p('PBKS', 11, 'Azmatullah Omarzai', 'AR', 8.0),
  p('PBKS', 12, 'Priyansh Arya', 'BAT', 8.0),
  p('PBKS', 13, 'Musheer Khan', 'AR', 6.5),
  p('PBKS', 14, 'Suryansh Shedge', 'AR', 6.5),
  p('PBKS', 15, 'Mitch Owen', 'AR', 7.0),
  p('PBKS', 16, 'Cooper Connolly', 'AR', 7.5),
  p('PBKS', 17, 'Ben Dwarshuis', 'BOWL', 7.5),
  p('PBKS', 18, 'Arshdeep Singh', 'BOWL', 9.0),
  p('PBKS', 19, 'Yuzvendra Chahal', 'BOWL', 8.5),
  p('PBKS', 20, 'Vyshak Vijaykumar', 'BOWL', 7.5),
  p('PBKS', 21, 'Yash Thakur', 'BOWL', 7.0),
  p('PBKS', 22, 'Xavier Bartlett', 'BOWL', 7.0),
  p('PBKS', 23, 'Pravin Dubey', 'BOWL', 7.0),
  p('PBKS', 24, 'Vishal Nishad', 'BOWL', 6.5),
  p('PBKS', 25, 'Lockie Ferguson', 'BOWL', 8.0),

  // ── GT ──
  p('GT', 1, 'Shubman Gill', 'BAT', 9.0),
  p('GT', 2, 'Sai Sudharsan', 'BAT', 9.0),
  p('GT', 3, 'Glenn Phillips', 'AR', 8.0),
  p('GT', 4, 'Jos Buttler', 'WK', 8.5),
  p('GT', 5, 'Kumar Kushagra', 'WK', 6.5),
  p('GT', 6, 'Anuj Rawat', 'WK', 6.0),
  p('GT', 7, 'Tom Banton', 'BAT', 7.5),
  p('GT', 8, 'Nishant Sindhu', 'AR', 6.5),
  p('GT', 9, 'Washington Sundar', 'AR', 7.5),
  p('GT', 10, 'Mohd Arshad Khan', 'BOWL', 6.5),
  p('GT', 11, 'Sai Kishore', 'BOWL', 8.0),
  p('GT', 12, 'Jayant Yadav', 'BOWL', 7.0),
  p('GT', 13, 'Jason Holder', 'AR', 8.0),
  p('GT', 14, 'Rahul Tewatia', 'BAT', 6.5),
  p('GT', 15, 'Shahrukh Khan', 'BAT', 7.0),
  p('GT', 16, 'Kagiso Rabada', 'BOWL', 8.5),
  p('GT', 17, 'Mohammed Siraj', 'BOWL', 8.5),
  p('GT', 18, 'Prasidh Krishna', 'BOWL', 8.0),
  p('GT', 19, 'Manav Suthar', 'AR', 6.0),
  p('GT', 20, 'Gurnoor Singh Brar', 'BOWL', 6.0),
  p('GT', 21, 'Ishant Sharma', 'BOWL', 7.0),
  p('GT', 22, 'Ashok Sharma', 'BOWL', 6.0),
  p('GT', 23, 'Luke Wood', 'BOWL', 6.5),
  p('GT', 24, 'Kulwant Khejroliya', 'BOWL', 7.0),
  p('GT', 25, 'Rashid Khan', 'BOWL', 8.5),
  p('GT', 26, 'Prem Raj Yarra', 'BOWL', 5.5),

  // ── LSG ──
  p('LSG', 1, 'Rishabh Pant', 'WK', 9.5),
  p('LSG', 2, 'Mukul Choudhary', 'WK', 6.0),
  p('LSG', 3, 'Josh Inglis', 'WK', 7.5),
  p('LSG', 4, 'Nicholas Pooran', 'WK', 7.5),
  p('LSG', 5, 'Aiden Markram', 'BAT', 8.0),
  p('LSG', 6, 'Himmat Singh', 'BAT', 6.5),
  p('LSG', 7, 'Matthew Breetzke', 'BAT', 6.5),
  p('LSG', 8, 'Akshat Raghuwanshi', 'BAT', 6.0),
  p('LSG', 9, 'Mitchell Marsh', 'AR', 8.0),
  p('LSG', 10, 'Abdul Samad', 'AR', 7.0),
  p('LSG', 11, 'Shahbaz Ahamad', 'AR', 7.0),
  p('LSG', 12, 'Arshin Kulkarni', 'AR', 7.0),
  p('LSG', 13, 'Wanindu Hasaranga', 'AR', 8.0),
  p('LSG', 14, 'Ayush Badoni', 'AR', 7.5),
  p('LSG', 15, 'Mohammad Shami', 'BOWL', 8.0),
  p('LSG', 16, 'Avesh Khan', 'BOWL', 6.0),
  p('LSG', 17, 'M Siddharth', 'BOWL', 6.0),
  p('LSG', 18, 'Digvesh Singh', 'BOWL', 6.0),
  p('LSG', 19, 'Akash Singh', 'BOWL', 6.0),
  p('LSG', 20, 'Prince Yadav', 'BOWL', 6.0),
  p('LSG', 21, 'Arjun Tendulkar', 'BOWL', 6.0),
  p('LSG', 22, 'Anrich Nortje', 'BOWL', 7.5),
  p('LSG', 23, 'Naman Tiwari', 'BOWL', 6.0),
  p('LSG', 24, 'Mayank Yadav', 'BOWL', 7.5),
  p('LSG', 25, 'Mohsin Khan', 'BOWL', 6.0),

  // ── RR ──
  p('RR', 1, 'Yashasvi Jaiswal', 'BAT', 9.0),
  p('RR', 2, 'Shimron Hetmyer', 'BAT', 8.5),
  p('RR', 3, 'Vaibhav Suryavanshi', 'BAT', 8.5),
  p('RR', 4, 'Shubham Dubey', 'BAT', 7.0),
  p('RR', 5, 'Aman Rao Perala', 'BAT', 6.0),
  p('RR', 6, 'Dhruv Jurel', 'WK', 8.0),
  p('RR', 7, 'Donovan Ferreira', 'AR', 7.5),
  p('RR', 8, 'Lhuan-dre Pretorius', 'WK', 7.0),
  p('RR', 9, 'Ravi Singh', 'WK', 6.0),
  p('RR', 10, 'Riyan Parag', 'AR', 8.5),
  p('RR', 11, 'Yudhvir Singh Charak', 'AR', 7.0),
  p('RR', 12, 'Ravindra Jadeja', 'AR', 8.5),
  p('RR', 13, 'Dasun Shanaka', 'AR', 8.0),
  p('RR', 14, 'Jofra Archer', 'BOWL', 8.5),
  p('RR', 15, 'Tushar Deshpande', 'BOWL', 7.5),
  p('RR', 16, 'Kwena Maphaka', 'BOWL', 6.5),
  p('RR', 17, 'Ravi Bishnoi', 'BOWL', 8.0),
  p('RR', 18, 'Sushant Mishra', 'BOWL', 6.0),
  p('RR', 19, 'Yash Raj Punja', 'BOWL', 6.0),
  p('RR', 20, 'Vignesh Puthur', 'BOWL', 6.5),
  p('RR', 21, 'Brijesh Sharma', 'BOWL', 6.0),
  p('RR', 22, 'Adam Milne', 'BOWL', 7.5),
  p('RR', 23, 'Kuldeep Sen', 'BOWL', 7.0),
  p('RR', 24, 'Sandeep Sharma', 'BOWL', 8.0),
  p('RR', 25, 'Nandre Burger', 'BOWL', 7.5),
];

export function getPlayersByTeam(teamCode: string): Player[] {
  return IPL_PLAYERS.filter((p) => p.team === teamCode);
}

export function getPlayersForMatch(teamHomeCode: string, teamAwayCode: string): Player[] {
  return IPL_PLAYERS.filter((p) => p.team === teamHomeCode || p.team === teamAwayCode);
}

/** Resolve full team names (from IPL schedule) to team codes, then return combined players */
export function getMatchPlayers(teamHomeName: string, teamAwayName: string): Player[] {
  // Import inline to avoid circular deps — use the same logic as ipl.ts getTeamCode
  const nameToCode: Record<string, string> = {
    'royal challengers bengaluru': 'RCB',
    'mumbai indians': 'MI',
    'chennai super kings': 'CSK',
    'kolkata knight riders': 'KKR',
    'delhi capitals': 'DC',
    'punjab kings': 'PBKS',
    'rajasthan royals': 'RR',
    'sunrisers hyderabad': 'SRH',
    'gujarat titans': 'GT',
    'lucknow super giants': 'LSG',
  };

  const homeCode = nameToCode[teamHomeName.toLowerCase()] ?? teamHomeName.slice(0, 3).toUpperCase();
  const awayCode = nameToCode[teamAwayName.toLowerCase()] ?? teamAwayName.slice(0, 3).toUpperCase();

  return getPlayersForMatch(homeCode, awayCode);
}
